### PR TITLE
Fix #21 The left sidebar always shows child items

### LINKED ISSUE #21: Sidebar inner link are visible always
The inner(child) links inside the sidebar(left one) are always visible.

They would be ideally hidden if the parent is not selected
ie
https://example.docsy.dev/docs/tasks/
It only shows the inner link under the selected page and hide the rest

E.g.
https://example.docsy.dev/docs/concepts/
Here all the others are hidden since no child page is linked

So the expected behaviour is show child links only for the selected parent on the left sidebar.
Also in the original if the very top level is selected (documentation) it shows everything again.

### PR DESCRIPTION
**Pull request by gunhansancar**
Fix #21 The left sidebar always shows child items. With this commit it checks if the section is selected then it shows everything below that section or if a node is selected only shows its children.

Replaced slashes and captured the strings because of the forward slash differences in the urls.

### CODE REVIEW

**Comment by vsoch** [comment]
Taking a look!

**Comment by vsoch** [comment]
Thank you @gunhansancar !

**Comment by gunhansancar** [comment]
@vsoch Thanks for your efforts as well.
Yes, I tried to replicate the behaviour in the hugo theme. I actually want to have collapse/expend arrows. But I don't know what you think about it. Also this is good enough for me.

**Comment by vsoch** [comment]
My goal in creating this was to copy the original theme as much as I could, and honor those design decisions, so if the original has arrows it would make sense to add, otherwise not. I do think this is a needed change for documentation bases that are larger, and having everything expanded would make the left sidebar way too long / hard to navigate.

**Pull request merged**
