### PR TITLE
Support configurable branch

### PR DESCRIPTION
**Pull request by bhitney**
Added github_branch parameter to config to support branch name on edit link on editable.html.

### CODE REVIEW

**Comment by vsoch** [comment]
This is a great addition! Will you please bump the VERSION file from 0.0.21 to 0.0.22 and add a note to the changelog markdown?

**Comment by bhitney** [comment]
Sure, should be all set!

**Comment by vsoch** [comment]
This is a nitpick / question - but do you think GitHub / others are moving toward main, and perhaps the default should be main to encourage that?

**Comment by bhitney** [comment]
Yes -- the default should be main over master when creating a new repo. But, I left it master because it would break the edit page link for anyone still on master until they update their config. I'd recommend leaving it master unless there are very few theme users and everyone is ok with the break, or perhaps make it default in the next major release where multiple breaking changes can be rolled up in one release. 

All that said, there could be a better way of determining branch -- I didn't see it in any of the variables but not an expert on this, so this this seemed like an easy solution. :)

**Comment by vsoch** [comment]
That works for me! A lot of projects are still using master, so we can just address this in the future when main is more standard.

**Review by vsoch — APPROVED** [review]

**Comment by bhitney** [comment]
Thank you!  Although I just realized -- if someone uses this as a remote theme and does not have github_branch in their local _config.yml file, will the remote github_branch setting (currently master) persist? I didn't test that scenario.

**Comment by vsoch** [comment]
Yeah we could add `{% if site.github_branch %}{{ site.github_branch }}{% else %}master{% endif %}`

**Comment by vsoch** [comment]
See https://github.com/vsoch/docsy-jekyll/pull/43

**Pull request merged**
