### PR TITLE
Added support for multiple first-level sidebar headings

### PR DESCRIPTION
**Pull request by kieran-mackle**
I tidied the sidebar.html code a bit and made it so that you can have multiple first-level sidebar headings.

### CODE REVIEW

**Comment by vsoch** [comment]
And I’ll make some time to review tomorrow. Stay tuned! :)

**Comment by kieran-mackle** [comment]
I understand! I just did it for my own site so thought I would share. I am quite new to html but it looked as though there were some missing closing tags in the for loops. Adding them resulted in the behaviour I expected after adding items to toc.yml.
Thanks for reviewing!

**Comment by vsoch** [comment]
@kieran-mackle so just to verify what I'm seeing (the changes) - the sidebar stays open when you click a link? I don't see another level of nesting (e.g., for the current site if I add another level of children it doesn't show up:

```yaml
      children:
        - title: Quizzes
          url: "docs/extras/example-quiz"
          children:
          - title: Tags Page
            url: "tags"
```
Let me know how to reproduce what you changed so I can see (and let me know if it's just that the sidebar stays open, which is very good!)

**Comment by vsoch** [comment]
Oh I think I see - multiple bolded levels? 

image

This looks great to me - let's give the others a few days to look and review and I definitely think this would be great to have!

**Comment by kieran-mackle** [comment]
Yes that's correct, the multiple first-level bold headings. Glad you like it!

**Comment by vsoch** [comment]
I'm going to say let's go ahead with integrating this change - it's indeed very useful and nice looking. The final TODOs for the PR are to:

- bump the version up to 0.0.23 in the root VERSION file
- Add a note to the CHANGELOG to indicate the changes here

And then we can merge and release!

**Comment by vsoch** [comment]
Thank you again @kieran-mackle ! I tweeted your work as a thank you, feel free to share! https://twitter.com/vsoch/status/1416506158471282688

**Comment by kieran-mackle** [comment]
No worries! Glad you like it!

**Pull request merged**
