### PR TITLE
Close #27

### LINKED ISSUE #27: Issue: about.md has repo/user instead of user/repo for link generation
The about.md file uses {repo}/{user} instead of {user}/{repo}.

### PR DESCRIPTION
**Pull request by neotamias**
Swap around the user and repo on about.md for link generation

### CODE REVIEW

**Comment by vsoch** [comment]
Looks good, and thank you for fixing this! Should we bump the VERSION and update the change log too for a new release?

**Comment by neotamias** [comment]
Sounds good, I'll remember to do that when I make changes in future as
well. Love the theme, by the way! I'll definitely be contributing more
since I would love to add some features and such. It's a perfect theme for
my use on my pages, so I want to make it the perfect theme for more! :)

**Comment by vsoch** [comment]
Normally when a maintainer asks to update a PR, this isn't for a "next time" but a request to do it now. You are very kind so I will do it for you this first time, and I look forward to you doing it next time :) Happy new Year!

**Comment by neotamias** [comment]
Oh sorry, I didn't know. I'm new to using github so I'm not familiar with
the etiquette.

**Comment by vsoch** [comment]
No worries! You'll know next time.. Welcome to GitHub!

**Pull request merged**
