### PR TITLE
Adding tags syndication page and documentation for how to use it

### LINKED ISSUE #7: [Feature request] Tag support
## Feature idea

Adding tags (keywords) in frontmatter (meta-data) will generate a page referencing all pages containing this page.

Example:

In frontmatter you add (in YAML for example):

```yaml
---
title: My Document
summary: A brief description of my document.
authors:
    - Waylan Limberg
    - Tom Christie
date: 2018-07-10
some_url: https://example.com*
tags:
    - dev
    - python
---
```

So it will create a endpoint http://example.org/tag/#dev and http://example.org/tag/#python referencing, respectively, all pages containing the dev tag and the python tag.

Then on the page of the documentation where there is such a tags frontmatter, the page will contain some tag link #dev and #python respectively referencing the previously mentioned endpoints.

## Related

The feature already exists in Jekyll, there is just to use it in the theme :)

A more heated discussion on why it is useful to have tags on documentation : https://github.com/mkdocs/mkdocs/issues/1828

Similar issue in Jekyll documentation themes:

- https://github.com/pmarsceill/just-the-docs/issues/255

## Example

This feature is already introduced in [Documentation Next](https://jekyll-themes.com/documentation-next/) Jekyll theme.

See https://idratherbewriting.com/documentation-theme-jekyll-next-version/sample1.html
image

### PR DESCRIPTION
**Pull request by vsoch**
This pull request will add a primary "tags" page where tags specified in both docs and posts will be syndicated, and link back to their sources. I've also updated the Customization -> Tags documentation to reflect how this works:

 - if the user defines `tag_search_endpoint` this will mean tags on pages/posts continue to link to that endpoint. The tags page that links to the posts can still be used in this case.
 - if the user comments out `tag_search_endpoint`, the tags on pages/posts will link to the tag on the tags page.

Tags are not implemented natively in jekyll, so this is an implementation that I came up with. To test:

```bash
git clone -b add/tags https://github.com/vsoch/docsy-jekyll
cd docsy-jekyll
bundle exec jekyll serve
```
View the tags page (linked in the left navigation) and go to a page with a tag to see it still link to AskCI. Then you can stop the server, comment out the tag_search_endpoint in _config.yml, and restart the server to see the same pages tags link to the internal tags syndication page.

This will close #7

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

### CODE REVIEW

**Comment by noraj** [comment]
This is exactly it! 

According to the documentation `tag_search_endpoint` should be commented in `_config.yml` by default.

image

**Comment by vsoch** [comment]
Ah good catch! I was testing with and without, and forgot to change it back. Let me fix that up now.

**Comment by vsoch** [comment]
okay all set! https://github.com/vsoch/docsy-jekyll/pull/8/commits/6cc71f2687a8fa24572c6bedc3a653574dce7a33

Let me know when everything looks good, and we can merge.

**Comment by noraj** [comment]
LGTM

**Pull request merged**
