### PR TITLE
add support in footer to linkedin url

### PR DESCRIPTION
**Pull request by eitanbehar**

### CODE REVIEW

**Comment by vsoch** [comment]
This is great! A few tweaks before we merge:

## Alignment

The alignment of the icons for the parent docsy are in a row:

image

but the PR here has them stacked - could we have them in a row as well?

image

## Changelog and Version

We should have an entry in the changelog to describe the versions, and also update the `VERSION` file in the repository root to 0.0.21.

**Comment by eitanbehar** [comment]
Thanks for the prompt feedback. I would love to fix the commit. 
Where can I see the code for the row-aligned icons (just to be sure we are on the same baseline). 
`footer.html` on the parent repo only has a link to Twitter in the left margin, and the link to Github is aligned to the right.   
image

**Comment by vsoch** [comment]
Right here -> https://www.docsy.dev/docs/

That's correct - the GitHub icon should be on the right, but then other icons added on the left should be in a line.

**Comment by eitanbehar** [comment]
Thanks. Fixed, PR updated. I think it would be a good idea to squash the commits for a cleaner history.

**Review by vsoch — APPROVED** [review]

**Comment by vsoch** [comment]
Looks perfect! Thank you!

**Comment by eitanbehar** [comment]
Thanks to you for this nice and helpful project :)

**Pull request merged**
